#!/bin/sh

#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
##################### By: Rxyhn  ####################

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

## Environments
export PATH="${PATH}:${HOME}/.config/bspwm/bin"

# Parse colors from "~/.Xresources"
xrdb -override "${HOME}/.Xresources"

xrdb_query()
{
    [ -n "$XRDB_QUERY" ] || XRDB_QUERY="$(xrdb -query)"

    echo "$XRDB_QUERY" | while IFS=';' read -r STRING; do
        [ "${1}" = "${STRING%%\	*}" ] || continue
        echo "${STRING##*\	}"
        break
    done
}

getcolors()
{
    FOREGROUND="$(xrdb_query '*.foreground:')"
    BACKGROUND="$(xrdb_query '*.background:')"
    BLACK="$(xrdb_query '*.color0:')"
    RED="$(xrdb_query '*.color1:')"
    GREEN="$(xrdb_query '*.color2:')"
    YELLOW="$(xrdb_query '*.color3:')"
    BLUE="$(xrdb_query '*.color4:')"
    MAGENTA="$(xrdb_query '*.color5:')"
    CYAN="$(xrdb_query '*.color6:')"
    WHITE="$(xrdb_query '*.color7:')"
}

getcolors

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

# Run EWW.
# eww -c $HOME/.config/eww/bar --restart open bar &
$HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &

# Run notification daemon.
dunst --config $HOME/.config/dunst/dunstrc &

# Run Picom.
picom --config $HOME/.config/picom.conf &

# Run polkit daemon if doesn't started.
[ -n "$(pidof xfce-polkit)" ] || /usr/lib/xfce-polkit/xfce-polkit &

# Execute bspwm-specific scripts.
bspfloat &


# Fix cursor.
xsetroot -cursor_name cross 

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc monitor -d 1 2 3 4 5 6 7 8 9 

rule -a kitty                       follow=on focus=on
rule -a Code                        follow=on focus=on
rule -a firefox                     follow=on focus=on
rule mpv                            state=floating
rule feh                            state=floating

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [ "$state" != "fullscreen" ]; then
        continue
    fi
    if [ "$flag" == on ]; then
        $HOME/.local/bin/eww -c $HOME/.config/eww/bar close-all
  else
        $HOME/.local/bin/eww -c $HOME/.config/eww/bar open bar
    fi
done &

# Scratchpad



bspc rule -a kitty desktop='^1' follow=on focus=one
bspc rule -a code-oss desktop='^2' follow=on focus=one
bspc rule -a Org.gnome.Nautilus desktop='^3' follow=on focus=one
bspc rule -a firefox desktop='^4' follow=on focus=one
bspc rule -a Zathura desktop='^5' follow=on focus=one
bspc rule -a DesktopEditors desktop='^6' follow=on focus=one
bspc rule -a spotify desktop='^7' follow=on focus=one
bspc rule -a mpv desktop='^8' follow=on focus=one
bspc rule -a Vieb desktop='^9' follow=on focus=one state=tiled
bspc rule -a Pavucontrol desktop='^9' follow=on focus=one state=tiled
bspc rule -a Blueman-manager desktop='^9' follow=on focus=one state=tiled
bspc rule -a Nvidia-settings desktop='^9' follow=on focus=one state=tiled
bspc rule -a Plank state=floating layer=below manage=off border=off



config left_padding 55
config border_width 2
config window_gap 10
config split_ratio 0.52

config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer true

bspc config normal_border_color "$BACKGROUND"
bspc config focused_border_color "#ea6962"
config presel_feedback_color "$BACKGROUND"
# pkill borders ; borders &
~/.config/bspwm/autostart.sh &
